endpoints: 
  albums: https://api.spotify.com/v1/albums/{id}
  playlists: https://api.spotify.com/v1/playlists/{id}
  artists: https://api.spotify.com/v1/artists/{id}/top-tracks
  tracks: https://api.spotify.com/v1/tracks/{id}
  pssh: https://seektables.scdn.co/seektable/{file_id}.json
  metadata: https://spclient.wg.spotify.com/metadata/4/track/{gid}?market=from_token
  stream: https://gue1-spclient.spotify.com/storage-resolve/v2/files/audio/interactive/11/{file_id}?version=10000000&product=9&platform=39&alt=json
  license: https://gae2-spclient.spotify.com/widevine-license/v1/audio/license