user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36'

sp_dc: ''

default_quality: 'flac_24'

totp_secrets_url: 'https://git.gay/thereallo/totp-secrets/raw/branch/main/secrets/secretDict.json'

client_version: '1.2.87.27.ga2033a72'

endpoints:
  server_time: 'https://open.spotify.com/api/server-time'
  session_token: 'https://open.spotify.com/api/token'
  client_token: 'https://clienttoken.spotify.com/v1/clienttoken'
  web_api: 'https://api.spotify.com/v1'
  playback_info: 'https://gue1-spclient.spotify.com/track-playback/v1/media/spotify:{media_type}:{media_id}'
  storage_resolve: 'https://gue1-spclient.spotify.com/storage-resolve/v2/files/audio/interactive/{format_id}/{file_id}?version=10000000&product=9&platform=39&alt=json'
  widevine_license: 'https://gue1-spclient.spotify.com/widevine-license/v1/audio/license'
  pathfinder: 'https://api-partner.spotify.com/pathfinder/v2/query'

pathfinder_hashes:
  getTrack: '612585ae06ba435ad26369870deaae23b5c8800a256cd8a57e08eddc25a37294'
  getAlbum: 'b9bfabef66ed756e5e13f68a942deb60bd4125ec1f1be8cc42769dc0259b4b10'
  fetchPlaylist: 'bb67e0af06e8d6f52b531f97468ee4acd44cd0f82b988e15c2ea47b1148efc77'

playplay:
  enabled: false
  license_url: 'https://gew4-spclient.spotify.com/playplay/v1/key/{file_id}'
  session_type: 'librespot'
  spotify_binary_path: ''
  playplay_token: '02811027c51620c0fd36cd1de59e227a'
  formats:
    vorbis_low: 0
    vorbis_medium: 1
    vorbis_high: 2
    flac_flac: 16
    flac_flac_24: 22
