headers:
  User-Agent: "AndroidTV/!/!"
  x-tvnz-api-client-id: "androidtv/!.!.!"

endpoints:
  base_api: "https://apis-public-prod.tech.tvnz.co.nz"
  brightcove: "https://edge.api.brightcove.com/playback/v1/accounts/{}/videos/{}"

policy: "BCpkADawqM0IurzupiJKMb49WkxM__ngDMJ3GOQBhN2ri2Ci_lHwDWIpf4sLFc8bANMc-AVGfGR8GJNgxGqXsbjP1gHsK2Fpkoj6BSpwjrKBnv1D5l5iGPvVYCo"