endpoints:
  asset: https://valencia-app-mds.xumo.com/v2/assets/asset/{asset_id}.json

client:
  web:
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:149.0) Gecko/20100101 Firefox/149.0"