client:
  api_version: "Android/com.kanopy/6.21.0/952 (SM-A525F; Android 15)"
  user_agent: "okhttp/5.2.1"
  widevine_ua: "KanopyApplication/6.21.0 (Linux;Android 15) AndroidXMedia3/1.8.0"

endpoints:
  handshake: "https://www.kanopy.com/kapi/handshake"
  login: "https://www.kanopy.com/kapi/login"
  memberships: "https://www.kanopy.com/kapi/memberships?userId={user_id}"
  institutions: "https://www.kanopy.com/kapi/institutions/alias/{subdomain}"
  video_info: "https://www.kanopy.com/kapi/videos/{video_id}?domainId={domain_id}"
  video_items: "https://www.kanopy.com/kapi/videos/{video_id}/items?domainId={domain_id}"
  search: "https://www.kanopy.com/kapi/search/videos"
  plays: "https://www.kanopy.com/kapi/plays"
  widevine_license: "https://www.kanopy.com/kapi/licenses/widevine/{license_id}"
  playready_license: "https://www.kanopy.com/kapi/licenses/playready/{license_id}"