headers:
  user-agent: Dalvik/2.1.0 (Linux; U; Android 13; SM-A536E Build/RSR1.210722.013.A2)

endpoints:
  base_url: https://www.rte.ie
  feed: https://feed.entertainment.tv.theplatform.eu
  license: https://widevine.entitlement.eu.theplatform.com/wv/web/ModularDrm
