headers:
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
  accept-language: en-US,en;q=0.8

endpoints:
  base_url: https://api.iview.abc.net.au
  license: https://wv-keyos.licensekeyserver.com/
  
client: "1d4b5cba-42d2-403e-80e7-34565cdf772d"