headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"

endpoints:
  base: "https://watch.blaze.tv"
  series: "https://watch.blaze.tv/series"
  token: "https://watch.blaze.tv/api/player/token/{uvid}"
  streams: "https://v2-streams-elb.simplestreamcdn.com/api/{type}/stream/{uvid}"

playback:
  key: "6Pr3Uj2Fo3Ix7Rb9Ze9Ro4Ez2Eq7Sy"
  platform: "chrome"
